config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  devise_for :users
  root to: 'rooms#index'
  resources :users, only: [:edit, :update]
  resources :rooms do
    get 'join', to: 'join#index'
    post 'join', to: 'join#join'
    member do
      get 'show_users'
    end
    resources :manuals do
      collection do
        get 'search'
      end
    end
    resources :books do
      collection do
        get 'search'
      end
    end
    resources :items do
      collection do
        get 'search'
      end
    end
  end
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  belongs_to :room
  has_one_attached :image, dependent: :destroy

  validates :book_name, presence: true
  validates :book_number, presence: true, numericality: { only_integer: true, message: 'は半角数字で入力してください' }
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_room
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  def index
    @book = Book.where(room_id: params[:room_id]).order('created_at DESC')
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to room_books_path(@room, @book)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
  end

  def edit
  end

  def update
    if @book.update(book_params)
      redirect_to room_books_path(@room, @book)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @book.destroy
    redirect_to room_books_path(@room, @book)
  end

  def search
    if params[:keyword].present?
      @book = Book.where('book_name LIKE(?)', "%#{params[:keyword]}%")
    else
      @book = Book.where(room_id: params[:room_id]).order('created_at DESC')
    end
  end

  private

  def set_room
    @room = Room.find(params[:room_id])
  end

  def set_book
    @book = Book.find(params[:id])
  end

  def book_params
    params.require(:book).permit(:book_name, :book_number, :release_date, :book_memo, :image).merge(user_id: current_user.id, room_id: @room.id)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<%= render "shared/header" %>

<div class="edit-main">
  <div class="manual-registration-main">
    <div class="manual-registration-title">情報を入力</div>
    <%= form_with model: @book, url: room_book_path(@room, @book), id: 'new_registration', local: true do |f| %>

    <%# インスタンスを渡して、エラー発生時にメッセージが表示 %>
    <div class="error">
      <%= render 'shared/error_messages', model: f.object %>
    </div>
    
    <%# 商品画像 %>
    <div class="manual-image">
      <div class="manual-image-text">
        商品画像
      </div>

      <%# 画像プレビュー表示 %>
      <div class="preview-before">
        <% if @book.image.present? %>
          <%= image_tag(@book.image ) %> 
        <% else %>
          <%= image_tag("sample.png") %>
        <% end %>
      </div>
      <div id="previews"></div>
      <%# /画像プレビュー表示 %>

      <div class="manual-img"><%= f.file_field :image %></div>
    </div>
    <%# /商品画像 %>
    
    <%# 漫画名 %>
    <div class="manual-name">
      <div class="manual-title-text">
        漫画名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :book_name, class:"manual-name-input", placeholder:"漫画名（必須 40文字まで)", maxlength:"40" %>
    </div>
    <%# /漫画名 %>

    <%# 所持巻数 %>
    <div class="manual-number">
      <div class="manual-title-text">
        所持巻数
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :book_number, class:"manual-number-input", placeholder:"巻数", maxlength:"100" %>
    </div>
    <%# /所持巻数 %>

    <%# 次巻発売日 %>
    <div class="manual-assurance">
      <div class="manual-title-text">
        次巻発売予定日
      </div>
      <div class="manual-assurance-input">
        <%= raw sprintf(
                    f.date_select(
                      :release_date,
                      use_month_numbers: true,
                      prompt:'--',
                      start_year: (Time.now.year + 5),
                      end_year: (Time.now.year),
                      date_separator: '%s'),
                    "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>" %>
      </div>
    </div>
    <%# /次巻発売日 %>

    <%# メモ欄 %>
    <div class="manual-memo">
      <div class="manual-title-text">
        メモ欄
      </div>
      <%= f.text_area :book_memo, class:"manual-memo-input", placeholder:"メモ", rows:"7", maxlength:"1000" %>
    </div>
    <%# /メモ欄 %>

    <%# 下部ボタン %>
    <div class="manual-form-btn">
      <%= f.submit "更新" ,class:"manual-btn", data: { "turbo" => false } %>
    </div>
    <div class="manual-back-btn">
      <%=link_to 'もどる', :back %>
    </div>
    <%# /下部ボタン %>
    <% end %>
  </div>
</div>

app/views/books/index.html.erb
<%= render "shared/header" %>

<div class="search">
  <div class="search-left">漫画一覧</div>
  <%= form_with(url: search_room_books_path, local: true, method: :get) do |form| %>
    <%= form.text_field :keyword, placeholder: "漫画名で検索する", class: "search-input" %>
    <%= form.submit "検索", class: "search-btn" %>
  <% end %>
  <div class="search-right">
    <div class="manual-back"><%= link_to "メニューへ", room_path(@room) %></div>
    <div class="manual-back"><%= link_to "登録", new_room_book_path(@room) %></div>
  </div>
</div>

<div class="manual-list">
  <% @book.each do |book| %>
    <div class="manual">
      <div class="manual-image">
        <% if book.image.present? %>
          <%= link_to image_tag(book.image), room_book_path(@room, book) %> 
        <% else %>
          <%= link_to image_tag("sample.png"), room_book_path(@room, book) %>
        <% end %>
      </div>
      <div class="manual-name">
        <%= link_to book.book_name, room_book_path(@room, book) %>
      </div>
      <div class="manual-user">
        所持巻数：<%= book.book_number %>巻
      </div>
    </div>
  <% end %>
</div>

app/views/books/new.html.erb
<%= render "shared/header" %>

<div class="new-main">
  <div class="manual-registration-main">
    <div class="manual-registration-title">情報を入力</div>
    <%= form_with model: @book, url: room_books_path(@room), id: 'new_registration', local: true do |f| %>

    <%# インスタンスを渡して、エラー発生時にメッセージが表示 %>
    <div class="error">
      <%= render 'shared/error_messages', model: f.object %>
    </div>

    <%# 商品画像 %>
    <div class="manual-image">
      <div class="manual-title-text">
        商品画像
      </div>

      <%# 画像プレビュー表示 %>
      <div id="previews"></div>
      <%# /画像プレビュー表示 %>

      <div class="manual-img"><%= f.file_field :image %></div>
    </div>
    <%# /商品画像 %>
    
    <%# 漫画名 %>
    <div class="manual-name">
      <div class="manual-title-text">
        漫画名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :book_name, class:"manual-name-input", placeholder:"漫画名（必須 40文字まで)", maxlength:"40" %>
    </div>
    <%# /漫画名 %>

    <%# 所持巻数 %>
    <div class="manual-number">
      <div class="manual-title-text">
        所持巻数
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_field :book_number, class:"manual-number-input", placeholder:"巻数", maxlength:"100" %>
    </div>
    <%# /所持巻数 %>

    <%# 次巻発売日 %>
    <div class="manual-assurance">
      <div class="manual-title-text">
        次巻発売予定日
      </div>
      <div class="manual-assurance-input">
        <%= raw sprintf(
                    f.date_select(
                      :release_date,
                      use_month_numbers: true,
                      prompt:'--',
                      start_year: (Time.now.year + 5),
                      end_year: (Time.now.year),
                      date_separator: '%s'),
                    "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>" %>
      </div>
    </div>
    <%# /次巻発売日 %>

    <%# メモ欄 %>
    <div class="manual-memo">
      <div class="manual-title-text">
        メモ欄
      </div>
      <%= f.text_area :book_memo, class:"manual-memo-input", placeholder:"メモ", rows:"7", maxlength:"1000" %>
    </div>
    <%# /メモ欄 %>

    <%# 下部ボタン %>
    <div class="manual-form-btn">
      <%= f.submit "登録する" ,class:"manual-btn", data: { "turbo" => false } %>
    </div>
    <div class="manual-back-btn">
      <%=link_to 'もどる', :back %>
    </div>
    <%# /下部ボタン %>
    <% end %>
  </div>
</div>

app/views/books/search.html.erb
<%= render "shared/header" %>

<div class="search">
  <div class="search-left">漫画一覧</div>
  <%= form_with(url: search_room_books_path, local: true, method: :get) do |form| %>
    <%= form.text_field :keyword, placeholder: "漫画名で検索する", class: "search-input" %>
    <%= form.submit "検索", class: "search-btn" %>
  <% end %>
  <div class="search-right">
    <div class="manual-back"><%= link_to "メニューへ", room_path(@room) %></div>
    <div class="manual-back"><%= link_to "登録", new_room_book_path(@room) %></div>
  </div>
</div>

<div class="manual-list">
  <% @book.each do |book| %>
    <div class="manual">
      <div class="manual-image">
        <% if book.image.present? %>
          <%= link_to image_tag(book.image), room_book_path(@room, book) %> 
        <% else %>
          <%= link_to image_tag("sample.png"), room_book_path(@room, book) %>
        <% end %>
      </div>
      <div class="manual-name">
        <%= link_to book.book_name, room_book_path(@room, book) %>
      </div>
      <div class="manual-user">
        所持巻数：<%= book.book_number %>巻
      </div>
    </div>
  <% end %>
</div>

app/views/books/show.html.erb
<%= render "shared/header" %>

<div class="show-main">
  <div class="show-name"><%= @book.book_name %></div>
  <div class="show-btn">
    <div class="show-manual-btn"><%= link_to "編集", edit_room_book_path(@room, @book) %></div>
    <div class="show-manual-btn"><%= link_to "もどる", room_books_path(@room, @book) %></div>
    <div class="show-manual-btn"><%= link_to "削除する", room_book_path(@room, @book), data: { turbo_method: :delete, turbo_confirm: "本当に削除しますか？" } %></div>
  </div>
  <div class="show-main-sub">
    <div class="show-image">
      <% if @book.image.present? %>
        <%= image_tag(@book.image ) %> 
      <% else %>
        <%= image_tag("sample.png") %>
      <% end %>
    </div>
    <div class="detail-table">
        <div class="detail-tables">
          <div class="detail-item">登録者</div>
          <div class="detail-value"><%= @book.user.name %></div>
        </div>
        <div class="detail-tables">
          <div class="detail-item">所持巻数</div>
          <div class="detail-value"><%= @book.book_number %>巻</div>
        </div>
        <div class="detail-tables">
          <div class="detail-item">次巻発売予定日</div>
          <% if @book.release_date.present? %>
            <div class="detail-value"><%= @book.release_date %></div>
          <% else %>
            <div class="detail-value">データがありません</div>
          <% end %>
        </div>
        <div class="detail-tables">
          <div class="detail-items">メモ</div>
          <% if @book.book_memo.present? %>
            <div class="detail-values"><%= simple_format(@book.book_memo) %></div>
          <% else %>
            <div class="detail-values">データがありません</div>
          <% end %>
        </div>
    </div>
  </div>
</div>