config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  devise_for :users
  root to: 'rooms#index'
  resources :users, only: [:edit, :update]
  resources :rooms do
    get 'join', to: 'join#index'
    post 'join', to: 'join#join'
    member do
      get 'show_users'
    end
    resources :manuals do
      collection do
        get 'search'
      end
    end
    resources :books do
      collection do
        get 'search'
      end
    end
    resources :items do
      collection do
        get 'search'
      end
    end
  end
end

app/models/manual.rb
class Manual < ApplicationRecord
  belongs_to :user
  belongs_to :room
  has_one_attached :image, dependent: :destroy

  validates :manual_name, presence: true
  validates :price, numericality: { only_integer: true, message: 'は半角数字で入力してください' }, allow_blank: true
end

app/controllers/manuals_controller.rb
class ManualsController < ApplicationController
  before_action :set_room
  before_action :set_manual, only: [:show, :edit, :update, :destroy]

  def index
    @manual = Manual.where(room_id: params[:room_id]).order('created_at DESC')
  end

  def new
    @manual = Manual.new
  end

  def create
    @manual = Manual.new(manual_params)
    if @manual.save
      redirect_to room_manuals_path(@room, @manual)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
  end

  def edit
  end

  def update
    if @manual.update(manual_params)
      redirect_to room_manuals_path(@room, @manual)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @manual.destroy
    redirect_to room_manuals_path(@room, @manual)
  end

  def search
    if params[:keyword].present?
      @manual = Manual.where('manual_name LIKE(?)', "%#{params[:keyword]}%")
    else
      @manual = Manual.where(room_id: params[:room_id]).order('created_at DESC')
    end
  end

  private

  def set_room
    @room = Room.find(params[:room_id])
  end

  def set_manual
    @manual = Manual.find(params[:id])
  end

  def manual_params
    params.require(:manual).permit(:manual_name, :model_number, :manual_url, :assurance, :manual_date, :price, :manual_memo, :image).merge(user_id: current_user.id, room_id: @room.id)
  end
end

app/helpers/manuals_helper.rb
module ManualsHelper
end

app/views/manuals/edit.html.erb
<%= render "shared/header" %>

<div class="edit-main">
  <div class="manual-registration-main">
    <div class="manual-registration-title">情報を入力</div>
    <%= form_with model: @manual, url: room_manual_path(@room, @manual), id: 'new_registration', local: true do |f| %>

    <%# インスタンスを渡して、エラー発生時にメッセージが表示 %>
    <div class="error">
      <%= render 'shared/error_messages', model: f.object %>
    </div>
    
    <%# 商品画像 %>
    <div class="manual-image">
      <div class="manual-image-text">
        商品画像
      </div>

      <%# 画像プレビュー表示 %>
      <div class="preview-before">
        <% if @manual.image.present? %>
          <%= image_tag(@manual.image ) %> 
        <% else %>
          <%= image_tag("sample.png") %>
        <% end %>
      </div>
      <div id="previews"></div>
      <%# /画像プレビュー表示 %>

      <div class="manual-img"><%= f.file_field :image %></div>
    </div>
    <%# /商品画像 %>
    
    <%# 商品名 %>
    <div class="manual-name">
      <div class="manual-title-text">
        商品名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :manual_name, class:"manual-name-input", placeholder:"商品名（必須 40文字まで)", maxlength:"40" %>
    </div>
    <%# /商品名 %>

    <%# 型番 %>
    <div class="manual-number">
      <div class="manual-title-text">
        商品の型番
      </div>
      <%= f.text_area :model_number, class:"manual-number-input", placeholder:"商品の型番", maxlength:"100" %>
    </div>
    <%# /型番 %>

    <%# 取扱説明書のURL %>
    <div class="manual-url">
      <div class="manual-title-text">
        商品の取扱説明書のURL
      </div>
      <%= f.text_area :manual_url, class:"manual-url-input", placeholder:"URL", maxlength:"100" %>
    </div>
    <%# /取扱説明書のURL %>

    <%# 保証期限 %>
    <div class="manual-assurance">
      <div class="manual-title-text">
        商品の保証期限
      </div>
      <div class="manual-assurance-input">
        <%= raw sprintf(
                    f.date_select(
                      :assurance,
                      use_month_numbers: true,
                      prompt:'--',
                      start_year: (Time.now.year + 10),
                      end_year: (Time.now.year),
                      date_separator: '%s'),
                    "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>" %>
      </div>
    </div>
    <%# /保証期限 %>

    <%# 商品の購入日 %>
    <div class="manual-date">
      <div class="manual-title-text">
        商品の購入日
      </div>
      <div class="manual-date-input">
        <%= raw sprintf(
                    f.date_select(
                      :manual_date,
                      use_month_numbers: true,
                      prompt:'--',
                      start_year: (Time.now.year - 10),
                      end_year: (Time.now.year),
                      date_separator: '%s'),
                    "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>" %>
      </div>
    </div>
    <%# /商品の購入日 %>

    <%# 商品価格 %>
    <div class="manual-price">
      <div class="manual-title-text">
        商品の購入価格
      </div>
      <span class="sell-yen">¥</span>
      <%= f.text_field :price, class:"manual-price-input", placeholder:"例）5000" %>
    </div>
    <%# /商品価格 %>

    <%# メモ欄 %>
    <div class="manual-memo">
      <div class="manual-title-text">
        メモ欄
      </div>
      <%= f.text_area :manual_memo, class:"manual-memo-input", placeholder:"メモ", rows:"7", maxlength:"1000" %>
    </div>
    <%# /メモ欄 %>

    <%# 下部ボタン %>
    <div class="manual-form-btn">
      <%= f.submit "更新" ,class:"manual-btn", data: { "turbo" => false } %>
    </div>
    <div class="manual-back-btn">
      <%=link_to 'もどる', :back %>
    </div>
    <%# /下部ボタン %>
    <% end %>
  </div>
</div>

app/views/manuals/index.html.erb
<%= render "shared/header" %>

<div class="search">
  <div class="search-left">取扱説明書一覧</div>
  <%= form_with(url: search_room_manuals_path, local: true, method: :get) do |form| %>
    <%= form.text_field :keyword, placeholder: "商品名で検索する", class: "search-input" %>
    <%= form.submit "検索", class: "search-btn" %>
  <% end %>
  <div class="search-right">
    <div class="manual-back"><%= link_to "メニューへ", room_path(@room) %></div>
    <div class="manual-back"><%= link_to "登録", new_room_manual_path(@room) %></div>
  </div>
</div>


<div class="manual-list">
  <% @manual.each do |manual| %>
    <div class="manual">
      <div class="manual-image">
        <% if manual.image.present? %>
          <%= link_to image_tag(manual.image), room_manual_path(@room, manual) %> 
        <% else %>
          <%= link_to image_tag("sample.png"), room_manual_path(@room, manual) %>
        <% end %>
      </div>
      <div class="manual-name">
        <%= link_to manual.manual_name, room_manual_path(@room, manual) %>
      </div>
      <div class="manual-user">
      </div>
    </div>
  <% end %>
</div>

app/views/manuals/new.html.erb
<%= render "shared/header" %>

<div class="new-main">
  <div class="manual-registration-main">
    <div class="manual-registration-title">情報を入力</div>
    <%= form_with model: @manual, url: room_manuals_path(@room), id: 'new_registration', local: true do |f| %>

    <%# インスタンスを渡して、エラー発生時にメッセージが表示 %>
    <div class="error">
      <%= render 'shared/error_messages', model: f.object %>
    </div>
    
    <%# 商品画像 %>
    <div class="manual-image">
      <div class="manual-title-text">
        商品画像
      </div>

      <%# 画像プレビュー表示 %>
      <div id="previews"></div>
      <%# /画像プレビュー表示 %>

      <div class="manual-img"><%= f.file_field :image %></div>
    </div>
    <%# /商品画像 %>
    
    <%# 商品名 %>
    <div class="manual-name">
      <div class="manual-title-text">
        商品名
        <span class="indispensable">必須</span>
      </div>

      <%= f.text_area :manual_name, class:"manual-name-input", placeholder:"商品名（必須 40文字まで)", maxlength:"40" %>
    </div>
    <%# /商品名 %>

    <%# 型番 %>
    <div class="manual-number">
      <div class="manual-title-text">
        商品の型番
      </div>
      <%= f.text_area :model_number, class:"manual-number-input", placeholder:"商品の型番", maxlength:"100" %>
    </div>
    <%# /型番 %>

    <%# 取扱説明書のURL %>
    <div class="manual-url">
      <div class="manual-title-text">
        商品の取扱説明書のURL
      </div>
      <%= f.text_area :manual_url, class:"manual-url-input", placeholder:"URL", maxlength:"300" %>
    </div>
    <%# /取扱説明書のURL %>

    <%# 保証期限 %>
    <div class="manual-assurance">
      <div class="manual-title-text">
        商品の保証期限
      </div>
      <div class="manual-assurance-input">
        <%= raw sprintf(
                    f.date_select(
                      :assurance,
                      use_month_numbers: true,
                      prompt:'--',
                      start_year: (Time.now.year + 10),
                      end_year: (Time.now.year),
                      date_separator: '%s'),
                    "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>" %>
      </div>
    </div>
    <%# /保証期限 %>

    <%# 商品の購入日 %>
    <div class="manual-date">
      <div class="manual-title-text">
        商品の購入日
      </div>
      <div class="manual-date-input">
        <%= raw sprintf(
                    f.date_select(
                      :manual_date,
                      use_month_numbers: true,
                      prompt:'--',
                      start_year: (Time.now.year - 10),
                      end_year: (Time.now.year),
                      date_separator: '%s'),
                    "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>" %>
      </div>
    </div>
    <%# /商品の購入日 %>

    <%# 商品価格 %>
    <div class="manual-price">
      <div class="manual-title-text">
        商品の購入価格
      </div>
      <span class="sell-yen">¥</span>
      <%= f.text_field :price, class:"manual-price-input", placeholder:"例）5000" %>
    </div>
    <%# /商品価格 %>

    <%# メモ欄 %>
    <div class="manual-memo">
      <div class="manual-title-text">
        メモ欄
      </div>
      <%= f.text_area :manual_memo, class:"manual-memo-input", placeholder:"メモ", rows:"7", maxlength:"1000" %>
    </div>
    <%# /メモ欄 %>

    <%# 下部ボタン %>
    <div class="manual-form-btn">
      <%= f.submit "登録する" ,class:"manual-btn", data: { "turbo" => false } %>
    </div>
    <div class="manual-back-btn">
      <%=link_to 'もどる', :back %>
    </div>
    <%# /下部ボタン %>
    <% end %>
  </div>
</div>

app/views/manuals/search.html.erb
<%= render "shared/header" %>

<div class="search">
  <div class="search-left">取扱説明書一覧</div>
  <%= form_with(url: search_room_manuals_path, local: true, method: :get) do |form| %>
    <%= form.text_field :keyword, placeholder: "商品名で検索する", class: "search-input" %>
    <%= form.submit "検索", class: "search-btn" %>
  <% end %>
  <div class="search-right">
    <div class="manual-back"><%= link_to "メニューへ", room_path(@room) %></div>
    <div class="manual-back"><%= link_to "登録", new_room_manual_path(@room) %></div>
  </div>
</div>


<div class="manual-list">
  <% @manual.each do |manual| %>
    <div class="manual">
      <div class="manual-image">
        <% if manual.image.present? %>
          <%= link_to image_tag(manual.image), room_manual_path(@room, manual) %> 
        <% else %>
          <%= link_to image_tag("sample.png"), room_manual_path(@room, manual) %>
        <% end %>
      </div>
      <div class="manual-name">
        <%= link_to manual.manual_name, room_manual_path(@room, manual) %>
      </div>
      <div class="manual-user">
      </div>
    </div>
  <% end %>
</div>

app/views/manuals/show.html.erb
<%= render "shared/header" %>

<div class="show-main">
  <div class="show-name"><%= @manual.manual_name %></div>
  <div class="show-btn">
    <div class="show-manual-btn"><%= link_to "編集", edit_room_manual_path(@room, @manual) %></div>
    <div class="show-manual-btn"><%= link_to "もどる", room_manuals_path(@room, @manual) %></div>
    <div class="show-manual-btn"><%= link_to "削除する", room_manual_path(@room, @manual), data: { turbo_method: :delete, turbo_confirm: "本当に削除しますか？" } %></div>
  </div>
  <div class="show-main-sub">
    <div class="show-image">
      <% if @manual.image.present? %>
        <%= image_tag(@manual.image ) %> 
      <% else %>
        <%= image_tag("sample.png") %>
      <% end %>
    </div>
    <div class="detail-table">
        <div class="detail-tables">
          <div class="detail-item">登録者</div>
          <div class="detail-value"><%= @manual.user.name %></div>
        </div>
        <div class="detail-tables">
          <div class="detail-item">型番</div>
          <% if @manual.model_number.present? %>
            <div class="detail-value"><%= @manual.model_number %></div>
          <% else %>
            <div class="detail-value">データがありません</div>
          <% end %>
        </div>
        <div class="detail-tables">
          <div class="detail-item">取扱説明書のURL</div>
          <% if @manual.manual_url.present? %>
            <div class="detail-value"><%= link_to @manual.manual_url, @manual.manual_url, target: "_blank" %></div>
          <% else %>
            <div class="detail-value">データがありません</div>
          <% end %>
        </div>
        <div class="detail-tables">
          <div class="detail-item">保証期限</div>
          <% if @manual.assurance.present? %>
            <div class="detail-value"><%= @manual.assurance %></div>
          <% else %>
            <div class="detail-value">データがありません</div>
          <% end %>
        </div>
        <div class="detail-tables">
          <div class="detail-item">購入日</div>
          <% if @manual.manual_date.present? %>
            <div class="detail-value"><%= @manual.manual_date %></div>
          <% else %>
            <div class="detail-value">データがありません</div>
          <% end %>
        </div>
        <div class="detail-tables">
          <div class="detail-item">購入価格</div>
          <% if @manual.price.present? %>
            <div class="detail-value"><%= @manual.price %></div>
          <% else %>
            <div class="detail-value">データがありません</div>
          <% end %>
        </div>
        <div class="detail-tables">
          <div class="detail-items">メモ</div>
          <% if @manual.manual_memo.present? %>
            <div class="detail-values"><%= simple_format(@manual.manual_memo) %></div>
          <% else %>
            <div class="detail-values">データがありません</div>
          <% end %>
        </div>
    </div>
  </div>
</div>