config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  devise_for :users
  root to: 'rooms#index'
  resources :users, only: [:edit, :update]
  resources :rooms do
    get 'join', to: 'join#index'
    post 'join', to: 'join#join'
    member do
      get 'show_users'
    end
    resources :manuals do
      collection do
        get 'search'
      end
    end
    resources :books do
      collection do
        get 'search'
      end
    end
    resources :items do
      collection do
        get 'search'
      end
    end
  end
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :room_users, dependent: :destroy
  has_many :users, through: :room_users
  has_many :manuals, dependent: :destroy
  has_many :books, dependent: :destroy
  has_many :items, dependent: :destroy

  validates :room_name,     presence: true, uniqueness: { scope: :room_password, message: 'とこのパスコードの組み合わせはすでに存在します' }
  validates :room_password, presence: true, format: { with: /\A\d{4}\z/, message: 'は4文字の半角数字で入力してください' }, uniqueness: { scope: :room_name }
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy, :show_users]

  def index
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    if @room.save
      redirect_to room_path(@room)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
  end

  def edit
  end

  def update
    if @room.update(room_params)
      redirect_to room_path(@room)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @room.destroy
    redirect_to rooms_path, notice: 'ルームは削除されました'
  end

  def show_users
  end

  private

  def set_room
    @room = Room.find(params[:id])
  end

  def room_params
    params.require(:room).permit(:room_name, :room_password, user_ids: [])
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/edit.html.erb
<%= render "shared/header" %>

<div class="room-main">
  <div class="room-page-left">
    <%= link_to image_tag("user-image.jpg", class:"room-page-image"), "#" %>
  </div>

  <%= form_with model: @room, class: "registration-form-main", local: true do |f|%>

    <div class="user-form-header">ルームの編集</div>

    <%= render 'shared/error_messages', model: f.object %>

    <div class="field">
      <label class="form-text">ルーム名</label>
        <%= f.text_field :room_name, class:"input-default" %>
    </div>

    <div class="field">
      <label class="form-text">パスコード</label>
      <%= f.text_field :room_password, class:"input-default" %>
    </div>

    <div class="actions">
      <%= f.submit "更新", class: "actions-btn"%>
    </div>

    <%= link_to "ルームを削除する", room_path(@room), data: { turbo_method: :delete, turbo_confirm: "本当に削除しますか？" }, class:"btn" %>
    <%= link_to "戻る", :back, class:"btn" %>

  <% end %>
</div>

app/views/rooms/index.html.erb
<%= render "shared/third-header"%>

<div class="room-main">
  <div class="room-page-left">
    <%= link_to image_tag("user-image.jpg", class:"room-page-image"), "#" %>
  </div>

  <div class="room-page-right">
    <%# 設定ボタン %>
    <%= image_tag("setting.jpg", id: "settingsIcon") %>
    <ul id="settingsList" class="hidden">
      <li><%= link_to "ユーザーの編集", edit_user_path(current_user) %></li>
      <li><%= link_to "ルームを作成", new_room_path %></li>
      <li><%= link_to "ルームに参加", room_join_path(current_user) %></li>
    </ul>
    
    <% if notice.present? %>
      <div class="room-notice">
        <%= notice %>
      </div>
    <% end %>

    <div class="user-room-header">マイルーム一覧</div>

    <% current_user.rooms.each do |room| %>
      <div class="room-name">
        <%= link_to room.room_name, room_path(room) %>
      </div>
    <% end %>

    <div class="room-page-create">
      <div class="room-btn">
        <%= link_to "ルームを作成", new_room_path %>
      </div>
      <div class="room-btn">
        <%= link_to "ルームに参加", room_join_path(current_user) %>
      </div>
    </div>
  </div>
</div>

app/views/rooms/new.html.erb
<%= render "shared/second-header"%>

<div class="room-main">
  <div class="room-page-left">
    <%= link_to image_tag("user-image.jpg", class:"room-page-image"), "#" %>
  </div>

  <%= form_with model: @room, class: 'room-form-main', local: true do |f| %>

    <div class="room-form-header">ルーム作成</div>

    <%= render 'shared/error_messages', model: f.object %>

    <div class="field">
      <label class="form-text">ルーム名</label>
      <%= f.text_field :room_name, class:"input-default", placeholder:"ルーム名を入力してください", maxlength:"40" %>
    </div>

    <div class="field">
      <label class="form-text">パスコード</label>
      <%= f.text_field :room_password, class:"input-default", placeholder:"4桁の半角数字" %>
    </div>

    <input name="room[user_ids][]" type="hidden" value=<%= current_user.id %>>

    <div class="actions">
      <%= f.submit "作成", class:"actions-btn" %>
    </div>

    <%= link_to "ルーム一覧ページ", rooms_path %>
  <% end %>

</div>

app/views/rooms/show.html.erb
<%= render "shared/header" %>

<div class="room-main">
  <div class="room-page-left">
    <%= link_to image_tag("user-image.jpg", class:"room-page-image"), "#" %>
  </div>

  <div class="room-show-right">
    <%# 設定ボタン %>
    <%= image_tag("setting.jpg", id: "settingsIcon") %>
    <ul id="settingsList" class="hidden">
      <li><%= link_to "ユーザーの編集", edit_user_path(current_user) %></li>
      <li><%= link_to "ルームの編集", edit_room_path(@room) %></li>
      <li><%= link_to "ルームに参加", room_join_path(current_user) %></li>
      <li><%= link_to "ルームメンバー", show_users_room_path(@room) %></li>
    </ul>

    <% if notice.present? %>
      <div class="room-notice">
        <%= notice %>
      </div>
    <% end %>

    <div class="room-manual"><%= link_to "取説一覧ページ", room_manuals_path(@room) %></div>
    <div class="room-book"><%= link_to "漫画一覧ページ", room_books_path(@room) %></div>
    <div class="room-item"><%= link_to "その他アイテム一覧ページ", room_items_path(@room) %></div>
    <%= link_to "ルーム一覧ページ", rooms_path %>
  </div>
</div>

app/views/rooms/show_users.html.erb
<%= render "shared/header" %>

<div class="room-main">
  <div class="room-page-left">
    <%= link_to image_tag("user-image.jpg", class:"room-page-image"), "#" %>
  </div>

  <div class="room-show-right">
    <%# 設定ボタン %>
    <%= image_tag("setting.jpg", id: "settingsIcon") %>
    <ul id="settingsList" class="hidden">
      <li><%= link_to "ユーザーの編集", edit_user_path(current_user) %></li>
      <li><%= link_to "ルームの編集", edit_room_path(@room) %></li>
    </ul>

    <div class="users-list-header">ルームメンバー</div>
    <ul class="users-list">
      <% @room.users.each do |user| %>
        <li class="user-list"><%= user.name %></li>
      <% end %>
    </ul>

    <%= link_to "戻る", room_path %>
  </div>
</div>