config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  devise_for :users
  root to: 'rooms#index'
  resources :users, only: [:edit, :update]
  resources :rooms do
    get 'join', to: 'join#index'
    post 'join', to: 'join#join'
    member do
      get 'show_users'
    end
    resources :manuals do
      collection do
        get 'search'
      end
    end
    resources :books do
      collection do
        get 'search'
      end
    end
    resources :items do
      collection do
        get 'search'
      end
    end
  end
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  belongs_to :room
  has_one_attached :image, dependent: :destroy

  validates :item_name, presence: true
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_room
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  def index
    @item = Item.where(room_id: params[:room_id]).order('created_at DESC')
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to room_items_path(@room, @item)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
  end

  def edit
  end

  def update
    if @item.update(item_params)
      redirect_to room_items_path(@room, @item)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @item.destroy
    redirect_to room_items_path(@room, @item)
  end

  def search
    if params[:keyword].present?
      @item = Item.where('item_name LIKE(?)', "%#{params[:keyword]}%")
    else
      @item = Item.where(room_id: params[:room_id]).order('created_at DESC')
    end
  end

  private

  def set_room
    @room = Room.find(params[:room_id])
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:item_name, :item_memo, :image).merge(user_id: current_user.id, room_id: @room.id)
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.erb
<%= render "shared/header" %>

<div class="edit-main">
  <div class="manual-registration-main">
    <div class="manual-registration-title">情報を入力</div>
    <%= form_with model: @item, url: room_item_path(@room, @item), id: 'new_registration', local: true do |f| %>

    <%# インスタンスを渡して、エラー発生時にメッセージが表示 %>
    <div class="error">
      <%= render 'shared/error_messages', model: f.object %>
    </div>
    
    <%# 商品画像 %>
    <div class="manual-image">
      <div class="manual-image-text">
        商品画像
      </div>

      <%# 画像プレビュー表示 %>
      <div class="preview-before">
        <% if @item.image.present? %>
          <%= image_tag(@item.image ) %> 
        <% else %>
          <%= image_tag("sample.png") %>
        <% end %>
      </div>
      <div id="previews"></div>
      <%# /画像プレビュー表示 %>

      <div class="manual-img"><%= f.file_field :image %></div>
    </div>
    <%# /商品画像 %>
    
    <%# 商品名 %>
    <div class="manual-name">
      <div class="manual-title-text">
        商品名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :item_name, class:"manual-name-input", placeholder:"漫画名（必須 40文字まで)", maxlength:"40" %>
    </div>
    <%# /商品名 %>

    <%# メモ欄 %>
    <div class="manual-memo">
      <div class="manual-title-text">
        メモ欄
      </div>
      <%= f.text_area :item_memo, class:"manual-memo-input", placeholder:"メモ", rows:"7", maxlength:"1000" %>
    </div>
    <%# /メモ欄 %>

    <%# 下部ボタン %>
    <div class="manual-form-btn">
      <%= f.submit "更新" ,class:"manual-btn", data: { "turbo" => false } %>
    </div>
    <div class="manual-back-btn">
      <%=link_to 'もどる', :back %>
    </div>
    <%# /下部ボタン %>
    <% end %>
  </div>
</div>

app/views/items/index.html.erb
<%= render "shared/header" %>

<div class="search">
  <div class="search-left">その他アイテム一覧</div>
  <%= form_with(url: search_room_items_path, local: true, method: :get) do |form| %>
    <%= form.text_field :keyword, placeholder: "商品名で検索する", class: "search-input" %>
    <%= form.submit "検索", class: "search-btn" %>
  <% end %>
  <div class="search-right">
    <div class="manual-back"><%= link_to "メニューへ", room_path(@room) %></div>
    <div class="manual-back"><%= link_to "登録", new_room_item_path(@room) %></div>
  </div>
</div>

<div class="manual-list">
  <% @item.each do |item| %>
    <div class="manual">
      <div class="manual-image">
        <% if item.image.present? %>
          <%= link_to image_tag(item.image), room_item_path(@room, item) %> 
        <% else %>
          <%= link_to image_tag("sample.png"), room_item_path(@room, item) %>
        <% end %>
      </div>
      <div class="manual-name">
        <%= link_to item.item_name, room_item_path(@room, item) %>
      </div>
      <div class="manual-user">
      </div>
    </div>
  <% end %>
</div>

app/views/items/new.html.erb
<%= render "shared/header" %>

<div class="new-main">
  <div class="manual-registration-main">
    <div class="manual-registration-title">情報を入力</div>
    <%= form_with model: @item, url: room_items_path(@room), id: 'new_registration', local: true do |f| %>

    <%# インスタンスを渡して、エラー発生時にメッセージが表示 %>
    <div class="error">
      <%= render 'shared/error_messages', model: f.object %>
    </div>

    <%# 商品画像 %>
    <div class="manual-image">
      <div class="manual-title-text">
        商品画像
      </div>

      <%# 画像プレビュー表示 %>
      <div id="previews"></div>
      <%# /画像プレビュー表示 %>

      <div class="manual-img"><%= f.file_field :image %></div>
    </div>
    <%# /商品画像 %>
    
    <%# 商品名 %>
    <div class="manual-name">
      <div class="manual-title-text">
        商品名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :item_name, class:"manual-name-input", placeholder:"商品名（必須 40文字まで)", maxlength:"40" %>
    </div>
    <%# /商品名 %>

    <%# メモ欄 %>
    <div class="manual-memo">
      <div class="manual-title-text">
        メモ欄
      </div>
      <%= f.text_area :item_memo, class:"manual-memo-input", placeholder:"メモ", rows:"7", maxlength:"1000" %>
    </div>
    <%# /メモ欄 %>

    <%# 下部ボタン %>
    <div class="manual-form-btn">
      <%= f.submit "登録する" ,class:"manual-btn", data: { "turbo" => false } %>
    </div>
    <div class="manual-back-btn">
      <%=link_to 'もどる', :back %>
    </div>
    <%# /下部ボタン %>
    <% end %>
  </div>
</div>

app/views/items/search.html.erb
<%= render "shared/header" %>

<div class="search">
  <div class="search-left">その他アイテム一覧</div>
  <%= form_with(url: search_room_items_path, local: true, method: :get) do |form| %>
    <%= form.text_field :keyword, placeholder: "商品名で検索する", class: "search-input" %>
    <%= form.submit "検索", class: "search-btn" %>
  <% end %>
  <div class="search-right">
    <div class="manual-back"><%= link_to "メニューへ", room_path(@room) %></div>
    <div class="manual-back"><%= link_to "登録", new_room_item_path(@room) %></div>
  </div>
</div>

<div class="manual-list">
  <% @item.each do |item| %>
    <div class="manual">
      <div class="manual-image">
        <% if item.image.present? %>
          <%= link_to image_tag(item.image), room_item_path(@room, item) %> 
        <% else %>
          <%= link_to image_tag("sample.png"), room_item_path(@room, item) %>
        <% end %>
      </div>
      <div class="manual-name">
        <%= link_to item.item_name, room_item_path(@room, item) %>
      </div>
      <div class="manual-user">
      </div>
    </div>
  <% end %>
</div>

app/views/items/show.html.erb
<%= render "shared/header" %>

<div class="show-main">
  <div class="show-name"><%= @item.item_name %></div>
  <div class="show-btn">
    <div class="show-manual-btn"><%= link_to "編集", edit_room_item_path(@room, @item) %></div>
    <div class="show-manual-btn"><%= link_to "もどる", room_items_path(@room, @item) %></div>
    <div class="show-manual-btn"><%= link_to "削除する", room_item_path(@room, @item), data: { turbo_method: :delete, turbo_confirm: "本当に削除しますか？" } %></div>
  </div>
  <div class="show-main-sub">
    <div class="show-image">
      <% if @item.image.present? %>
        <%= image_tag(@item.image ) %> 
      <% else %>
        <%= image_tag("sample.png") %>
      <% end %>
    </div>
    <div class="detail-table">
        <div class="detail-tables">
          <div class="detail-item">登録者</div>
          <div class="detail-value"><%= @item.user.name %></div>
        </div>
        <div class="detail-tables">
          <div class="detail-items">メモ</div>
          <% if @item.item_memo.present? %>
            <div class="detail-values"><%= simple_format(@item.item_memo) %></div>
          <% else %>
            <div class="detail-values">データがありません</div>
          <% end %>
        </div>
    </div>
  </div>
</div>